supabase:
  url: ${SUPABASE_URL}
  anon: ${SUPABASE_ANON_KEY}
  jwt_secret: ${SUPABASE_JWT_SIGNER}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: coding

  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_CLASS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWD}

  exposed:
    generate-ddl: true
    show-sql: true