spring:
  application:
    name: coding

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  exposed:
    generate-ddl: true
    show-sql: true