spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: coding

  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_CLASS}
    username: ${DB_NAME}
    password: ${DB_PASSWD}

  exposed:
    generate-ddl: true
    show-sql: true